/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.util.Arrays;
/**
 *
 * @author bmmar
 */
public class StatCalculator extends javax.swing.JPanel {

    /**
     * Creates new form StatCalculator
     */
    public StatCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputValues = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CalculateBtn = new javax.swing.JButton();
        mean = new javax.swing.JTextField();
        median = new javax.swing.JTextField();
        variance = new javax.swing.JTextField();
        stdDev = new javax.swing.JTextField();
        meanLbl = new javax.swing.JLabel();
        medianLbl = new javax.swing.JLabel();
        varianceLbl = new javax.swing.JLabel();
        stdDevLbl = new javax.swing.JLabel();
        range = new javax.swing.JTextField();
        CV = new javax.swing.JTextField();
        IQR = new javax.swing.JTextField();
        skew = new javax.swing.JTextField();
        rangeLbl = new javax.swing.JLabel();
        CVLbl = new javax.swing.JLabel();
        IQRLbl = new javax.swing.JLabel();
        skewLbl = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        title.setText("Statistics Calculator");

        inputValues.setColumns(20);
        inputValues.setRows(5);
        jScrollPane1.setViewportView(inputValues);

        jLabel2.setText("Enter values,");

        jLabel3.setText("separated by");

        jLabel4.setText("commas.");

        CalculateBtn.setText("Calculate");
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });

        mean.setText(" ");

        variance.setText("  ");

        stdDev.setText(" ");

        meanLbl.setText("Mean");

        medianLbl.setText("Median");

        varianceLbl.setText("Variance    ");

        stdDevLbl.setText("Std. Dev.");

        range.setText(" ");

        IQR.setText("  ");

        skew.setText(" ");

        rangeLbl.setText("Range");

        CVLbl.setText("CV");

        IQRLbl.setText("IQR");

        skewLbl.setText("Skew");

        error.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rangeLbl)
                            .addComponent(range, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(CV, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(CVLbl)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IQR, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(IQRLbl)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(skew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(skewLbl))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(meanLbl)
                                    .addComponent(mean, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(median, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(medianLbl)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(varianceLbl)
                                    .addComponent(variance, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(stdDev, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(stdDevLbl))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CalculateBtn)
                                .addGap(74, 74, 74)))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateBtn)
                    .addComponent(error))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(median, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(variance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanLbl)
                    .addComponent(medianLbl)
                    .addComponent(varianceLbl)
                    .addComponent(stdDevLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IQR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rangeLbl)
                    .addComponent(CVLbl)
                    .addComponent(IQRLbl)
                    .addComponent(skewLbl))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed
        error.setText("");
        String inputString[] = inputValues.getText().split(",");
        double values[] = new double[inputString.length];
        int i = 0;
        try {
            for (String s : inputString) {
                values[i] = Double.parseDouble(s);
                i++;
            } 
        } catch (NumberFormatException e) {
            error.setText("Error - Invalid input.");
            clearCalculations();
            return;
        }
        Arrays.sort(values);
        double mu = getMean(values);
        double var = getVariance(values, mu);
        mean.setText(Double.toString(round(mu)));
        median.setText(Double.toString(getMedian(values)));
        range.setText(Double.toString(values[values.length-1] - values[0]));
        variance.setText(Double.toString(round(var)));
        stdDev.setText(Double.toString(round(Math.sqrt(var))));
        CV.setText(Double.toString(round(Math.sqrt(var) / mu)));
        
        
    }//GEN-LAST:event_CalculateBtnActionPerformed

    private double getMean(double input[]) {
        double avg = 0.0;
        for (double d : input)
            avg += d;
        avg /= input.length;
        return avg;
    }
    
    private double getMedian(double input[]) {
        int half = input.length / 2 - 1;
        if (input.length % 2 == 0) //even
            return (input[half] + input[half+1]) / 2;
        else{
            return input[half+1];
        }
    }
    
    private double getVariance(double input[], double mu) {
        double v = 0.0;
        for (double d : input) 
            v += Math.pow(d - mu, 2);
        v /= input.length * 1.0;
        return v;
    }
    
    private double round(double in) {
        in = Math.round(in * 1000);
        in /= 1000;
        return in;
    }
    
    private void clearCalculations() {
        mean.setText("");
        median.setText("");
        variance.setText("");
        stdDev.setText("");
        range.setText("");
        CV.setText("");
        IQR.setText("");
        skew.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CV;
    private javax.swing.JLabel CVLbl;
    private javax.swing.JButton CalculateBtn;
    private javax.swing.JTextField IQR;
    private javax.swing.JLabel IQRLbl;
    private javax.swing.JLabel error;
    private javax.swing.JTextArea inputValues;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mean;
    private javax.swing.JLabel meanLbl;
    private javax.swing.JTextField median;
    private javax.swing.JLabel medianLbl;
    private javax.swing.JTextField range;
    private javax.swing.JLabel rangeLbl;
    private javax.swing.JTextField skew;
    private javax.swing.JLabel skewLbl;
    private javax.swing.JTextField stdDev;
    private javax.swing.JLabel stdDevLbl;
    private javax.swing.JLabel title;
    private javax.swing.JTextField variance;
    private javax.swing.JLabel varianceLbl;
    // End of variables declaration//GEN-END:variables
}
